# Generated by Django 4.2.7 on 2023-12-14 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChessBoard',
        ),
    ]
