# Generated by Django 4.2.7 on 2023-12-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
