# Generated by Django 4.2.7 on 2023-12-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_person_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('person_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password_encryption', models.CharField(max_length=300)),
                ('role', models.CharField(max_length=300)),
                ('last_login', models.DateTimeField()),
                ('is_logged_in', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('session_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField()),
                ('IP_address', models.GenericIPAddressField()),
                ('device_info', models.CharField(max_length=400)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='stranger',
            fields=[
                ('person_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=20)),
                ('is_banned', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='person',
        ),
    ]
