# Generated by Django 5.0 on 2023-12-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_employee_last_login_alter_session_logout_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='amer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello_name', models.CharField(max_length=300)),
            ],
        ),
    ]
