# Generated by Django 4.2.7 on 2023-12-16 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_amer'),
    ]

    operations = [
        migrations.CreateModel(
            name='entry_record',
            fields=[
                ('entry_record_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('reason_for_entry', models.CharField(max_length=300)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('out_date', models.DateTimeField(auto_now=True)),
                ('stranger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stranger')),
            ],
        ),
        migrations.CreateModel(
            name='security_note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1000)),
                ('entry_record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.entry_record')),
                ('stranger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stranger')),
            ],
        ),
        migrations.DeleteModel(
            name='amer',
        ),
        migrations.AddConstraint(
            model_name='security_note',
            constraint=models.UniqueConstraint(fields=('entry_record_id', 'stranger_id'), name='entry_record_stranger_id'),
        ),
    ]
