# Generated by Django 4.2.7 on 2023-12-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_security_note_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('vehicle_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('vehicle_color', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=200)),
                ('vehicle_state', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='cars',
            field=models.ManyToManyField(to='app.vehicle'),
        ),
    ]
