# Generated by Django 4.2.7 on 2023-12-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_vehicle_employee_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cars',
        ),
        migrations.AddField(
            model_name='stranger',
            name='cars',
            field=models.ManyToManyField(to='app.vehicle'),
        ),
    ]
